services:
  - type: web
    name: agroplay
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install && cd .. && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

